### ISSUE TITLE
Add missing images and fonts

### ISSUE THREAD

**Issue by alexbaumgertner** [ThreadsMobileLib/edna-sdk-web#1]
According https://github.com/ThreadsMobileLib/threads-sdk-web-gate/blob/master/threadswidget-3.16.0.min.css it should be images and fonts in repo.

For example, see threadswidget-3.16.0.min.css

```css
.rate_icon {
  background-image:url(/images/36e2143fa1f6f94dbee13d9c7989583e.svg);
}

/*...*/
url(/fonts/emojiSymb-5016bfad4b63066bb2843fdbb0e6ed8e.woff2)
```
